from dataclasses import dataclass
from typing import List, Any

from taiga_client.models.base import Base
from taiga_client.models.fields import Field


@dataclass
class ProjectItem(Base):
    anon_permissions: List[Any] = Field()
    blocked_code: Any = Field()
    creation_template: int = Field()
    default_epic_status: int = Field()
    default_issue_status: int = Field()
    default_issue_type: int = Field()
    default_points: int = Field()
    default_priority: int = Field()
    default_severity: int = Field()
    default_task_status: int = Field()
    default_us_status: int = Field()
    description: str = Field()
    i_am_admin: bool = Field()
    i_am_member: bool = Field()
    i_am_owner: bool = Field()
    is_backlog_activated: bool = Field()
    is_contact_activated: bool = Field()
    is_epics_activated: bool = Field()
    is_fan: bool = Field()
    is_featured: bool = Field()
    is_issues_activated: bool = Field()
    is_kanban_activated: bool = Field()
    is_looking_for_people: bool = Field()
    is_private: bool = Field()
    is_watcher: bool = Field()
    is_wiki_activated: bool = Field()
    logo_big_url: str = Field()
    logo_small_url: str = Field()
    looking_for_people_note: str = Field()
    members: List[int] = Field()
    my_homepage:  bool = Field()
    my_permissions: List[str] = Field()
    name:  str = Field()
    notify_level: int = Field()
    owner: Any = Field()
    public_permissions: List[Any] = Field()
    slug:  str = Field()
    tags: List[Any] = Field()
    tags_colors: Any = Field()
    total_activity: int = Field()
    total_activity_last_month: int = Field()
    total_activity_last_week: int = Field()
    total_activity_last_year: int = Field()
    total_closed_milestones: int = Field()
    total_fans: int = Field()
    total_fans_last_month: int = Field()
    total_fans_last_week: int = Field()
    total_fans_last_year: int = Field()
    total_milestones:  int = Field()
    total_story_points:  int = Field()
    total_watchers:  int = Field()
    totals_updated_datetime:  str = Field()
    videoconferences: Any = Field()
    videoconferences_extra_data: Any = Field()
